# Generated by Django 4.2.7 on 2024-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureforecast',
            name='district_name',
            field=models.CharField(default='Unknown District', max_length=255),
        ),
    ]
